# Generated by Django 4.0.8 on 2022-12-07 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='cnt',
            field=models.IntegerField(null=True, verbose_name='count'),
        ),
    ]
