# Generated by Django 4.0.8 on 2022-12-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_alter_count_cnt'),
    ]

    operations = [
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emotion', models.CharField(max_length=300)),
                ('seaon', models.CharField(max_length=300)),
                ('first', models.CharField(max_length=300)),
                ('second', models.CharField(max_length=300)),
                ('third', models.CharField(max_length=300)),
                ('fourth', models.CharField(max_length=300)),
                ('fifth', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='count',
        ),
    ]
