# Generated by Django 4.0.8 on 2022-12-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_food_delete_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='food',
            new_name='fullist',
        ),
    ]
