# Generated by Django 4.0.8 on 2022-12-08 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_rename_food_fullist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fullist',
            old_name='emotion',
            new_name='emot',
        ),
        migrations.RenameField(
            model_name='fullist',
            old_name='seaon',
            new_name='sea',
        ),
    ]
