# Generated by Django 4.0.8 on 2022-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_alter_fullist_emot_alter_fullist_fifth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullist',
            name='cr_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
