# Generated by Django 4.0.8 on 2022-12-09 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_choice_restaurantmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='cr_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
