# Generated by Django 4.0.8 on 2022-12-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0018_choice_cr_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='emotion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='menu',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='res',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
