# Generated by Django 4.0.8 on 2022-12-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_choice_emotion_choice_menu_alter_choice_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='season',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='weather',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
